In [1]:
# Tecnología
import json
import calendar
import pandas as pd
from sparky_bc import Sparky
import datetime as dt
from dateutil.relativedelta import relativedelta

# files lz conection
path_sparky_conf = '/Users/santlond/Documents/sparky_conf.json'

# Configurar conexión a LZ
with open(path_sparky_conf, 'rb') as JSON_lz_File:
    sp_config = json.loads(JSON_lz_File.read())
    
USER='santlond'
PASS=sp_config['ID']
DSN='IMPALA_PROD'
LOGDIR= 'logs'
# sparky = Sparky(username=USER, password=PASS, dsn=DSN, hostname="sbmdeblze004.bancolombia.corp")
sparky = Sparky(username=USER, password=PASS, dsn=DSN, hostname="sbmdeblze004.bancolombia.corp", spark_submit="spark3-submit")
 
# sparky = Sparky(username=USER, password=PASS, dsn=DSN)

helper = sparky.helper

/Users/santlond/Documents/venv_py39_odbc/lib/python3.9/site-packages/helper/helper.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
2026-08-18 16:26:09 - [WARNING] - No se encontro la carpeta "/Users/santlond/Documents/mmm_tdc/logs" para guardar los logs

 ____  _____ __  __  ___ _____ _____
|  _ \| ____|  \/  |/ _ \_   _| ____|
| |_) |  _| | |\/| | | | || | |  _|
|  _ <| |___| |  | | |_| || | | |___
|_| \_\_____|_|  |_|\___/ |_| |_____|

 ____  ____   _    ____  _  __
/ ___||  _ \ / \  |  _ \| |/ /
\___ \| |_) / _ \ | |_) | ' /
 ___) |  __/ ___ \|  _ <| . \
|____/|_| /_/   \_\_| \_\_|\_\

# Introducción

 Se obtendrán el número de llamadas realizadas por BPO que intentan rescatar clientes que no pudieron terminar la obtención de tarjeta de crédito por el canal digital.

In [2]:
# Nombre columnas
sql = """
DESCRIBE resultados_vspc_canales.bpo_gestionados
"""
nombre_columnas = helper.obtener_dataframe(sql)
nombre_columnas

2026-08-18 16:28:32 - [INFO] - Transcurrido: 1787088512, Tiempo de Refresco = 1000

----------------------------------------------------------------------------------------------
  i    tipo                    nombre                     estado     hora_inicio   duracion
----------------------------------------------------------------------------------------------
 1/1 DATAFRAME resultados_vspc_canales.bpo_gestionados   ejecutando   04:28:32 PM

2026-08-18 16:28:32 - [INFO] - 41 filas, 3 columnas, 00:00.2 consultando, 00:00.0 descargando, 00:00.0 convirtiendo

 1/1 DATAFRAME resultados_vspc_canales.bpo_gestionados   finalizado   04:28:32 PM     00:00.3
----------------------------------------------------------------------------------------------

                          name       type comment
0            f_entrega_informe  timestamp
1                      num_doc     bigint
2                     tipo_doc   smallint
3                prod_ofrecido     string
4                       modelo     string
5                  reg_validos     string
6             causal_no_valido     string
7                     desmonte     string
8                   gestionado     string
9                 f_gestionado  timestamp
10                hora_gestion     string
11                  contactado     string
12               desc_contacto     string
13                tel_contacto     string
14                     validez     string
15              causal_no_apto     string
16               venta_cantada     string
17                      codase     bigint
18              num_doc_asesor     bigint
19                 nivel_venta     string
20                      aliado     string
21                    id_venta     string
22                     f_venta  timestamp
23                 canal_venta     string
24               tipo_contacto     string
25             causal_no_venta     string
26               prod_aceptado     string
27                       monto        int
28                      moneda     string
29             revocatoria_sms     string
30           revocatoria_email     string
31      revocatoria_televentas     string
32  no_compartir_info_terceros     string
33              ingestion_year        int
34             ingestion_month        int
35               ingestion_day        int
36                num_producto     string
37                  franquicia     string
38                  tel_valido     string
39                        year        int
40                       month        int

In [4]:
# Última ingestion
ult_ing_bpo = helper.obtener_ultima_ingestion("resultados_vspc_canales.bpo_gestionados")
ult_ing_bpo

2026-08-18 16:40:22 - [INFO] - Buscando fechas para resultados_vspc_canales.bpo_gestionados
/Users/santlond/Documents/venv_py39_odbc/lib/python3.9/site-packages/helper/helper.py:476: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, cn)
/Users/santlond/Documents/venv_py39_odbc/lib/python3.9/site-packages/helper/helper.py:476: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, cn)
/Users/santlond/Documents/venv_py39_odbc/lib/python3.9/site-packages/helper/helper.py:476: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, cn)
2026-08-18 16:40:26 - [INFO] - Finalizo la busqueda, duracion: 00:04.4, resultado: {'year': 2026, 'month': 8, 'day': 14}

{'year': 2026, 'month': 8, 'day': 14}

In [6]:
', '.join(nombre_columnas['name'].tolist())

'f_entrega_informe, num_doc, tipo_doc, prod_ofrecido, modelo, reg_validos, causal_no_valido, desmonte, gestionado, f_gestionado, hora_gestion, contactado, desc_contacto, tel_contacto, validez, causal_no_apto, venta_cantada, codase, num_doc_asesor, nivel_venta, aliado, id_venta, f_venta, canal_venta, tipo_contacto, causal_no_venta, prod_aceptado, monto, moneda, revocatoria_sms, revocatoria_email, revocatoria_televentas, no_compartir_info_terceros, ingestion_year, ingestion_month, ingestion_day, num_producto, franquicia, tel_valido, year, month'

In [ ]:
# Obtener nombre de columnas de la tabla resultados_vspc_canales.bpo_gestionados

sql = f"""
SELECT {', '.join(nombre_columnas['name'].tolist())}
FROM resultados_vspc_canales.bpo_gestionados
WHERE YEAR = {ult_ing_bpo['year']}
  AND MONTH = {ult_ing_bpo['month']}
  AND ingestion_day = {ult_ing_bpo['day']}
"""
print(sql)

SELECT f_entrega_informe, num_doc, tipo_doc, prod_ofrecido, modelo, reg_validos, causal_no_valido, desmonte, gestionado, f_gestionado, hora_gestion, contactado, desc_contacto, tel_contacto, validez, causal_no_apto, venta_cantada, codase, num_doc_asesor, nivel_venta, aliado, id_venta, f_venta, canal_venta, tipo_contacto, causal_no_venta, prod_aceptado, monto, moneda, revocatoria_sms, revocatoria_email, revocatoria_televentas, no_compartir_info_terceros, ingestion_year, ingestion_month, ingestion_day, num_producto, franquicia, tel_valido, year, month
FROM resultados_vspc_canales.bpo_gestionados
WHERE YEAR = 2026
  AND MONTH = 8
  AND ingestion_day = 14

In [ ]:
sql = """
SELECT prod_ofrecido, count(*) as frecuencia
FROM resultados_vspc_canales.bpo_gestionados
WHERE YEAR BETWEEN 2024 and 2026
  AND MONTH BETWEEN 1 and 12
  AND ingestion_day BETWEEN 1 and 31
  AND regexp_like(prod_ofrecido, "TDC|TARJETA DE CREDITO|TARJETA_CREDITO|TC MULTIFRANQUICIA")
GROUP BY 1
ORDER BY prod_ofrecido;
"""

    year  mes  f_venta_ym  num_tdc_new  num_tdc_new_cumsum_ym
0   2026    8    20260801        17295                 207402
1   2026    7    20260701        27951                 190107
2   2026    6    20260601        26120                 162156
3   2026    5    20260501        22204                 136036
4   2026    4    20260401        30291                 113832
..   ...  ...         ...          ...                    ...
75  2020    5    20200501         2734                  26633
76  2020    4    20200401          401                  23899
77  2020    3    20200301         8126                  23498
78  2020    2    20200201         4948                  15372
79  2020    1    20200101        10424                  10424

[80 rows x 5 columns]

In [ ]:
# Escribir
df[['f_venta_ym', 'num_tdc_new']].to_excel('hist_data/ventas_tdc_digital_20240101_20260731.xlsx', index=False) # MODIFICAR nombre archivo. Cambia según fecha de ejecución.